import {
  ActivityLog,
  CropZone,
  DigitalTwinFarm,
  DiseasePrediction,
  FarmerProfile,
  KenyanMarketPrice,
  LeafDiagnosis,
  SaccoLoanOption,
  WeatherForecast,
  FarmAlert,
} from "./types";

export const MOCK_FARMER_PROFILE: FarmerProfile = {
  id: "farmer-001",
  fullName: "John Mokaya",
  phoneNumber: "+254 712 345 678",
  nationalId: "28491032",
  county: "Kiambu",
  subCounty: "Gatundu South",
  ward: "Kiamwangi",
  preferredLanguage: "en",
  saccoMembership: "Kiambu Farmers SACCO",
  memberNumber: "KFS-88421",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  experienceYears: 12,
};

export const MOCK_FARM: DigitalTwinFarm = {
  id: "farm-kiambu-01",
  farmName: "Kijani Ridge Smallholding",
  totalAcres: 3.8,
  perimeterMeters: 520,
  latitude: -1.0345,
  longitude: 36.9124,
  elevationMeters: 1720,
  soilType: "Humic Nitisols (Rich Red Volcanic Clay)",
  primaryWaterSource: "Borehole & Rainwater Harvesting",
  lastSatelliteSync: "2026-09-15 08:30 EAT (Sentinel-2)",
  lastIoTSync: "2 mins ago",
  mapped: true,
  primaryCrop: "White Maize",
  infrastructure: [
    { id: "inf-1", name: "Main Farmhouse", type: "Farmhouse", location: [0.45, 0.28], status: "Operational" },
    { id: "inf-2", name: "10,000L Roto Tank", type: "Water Tank", location: [0.55, 0.62], capacity: "10,000 Litres", status: "Operational" },
    { id: "inf-3", name: "Solar Borehole Pump", type: "Solar Pump", location: [0.58, 0.68], status: "Operational" },
    { id: "inf-4", name: "Produce Storage Shed", type: "Storage Barn", location: [0.38, 0.25], status: "Operational" },
    { id: "inf-5", name: "Bio-Slurry Compost Pit", type: "Compost Pit", location: [0.22, 0.78], status: "Operational" },
  ],
};

export const MOCK_ZONES: CropZone[] = [
  {
    id: "zone-1",
    name: "North Plot (Maize Block)",
    cropName: "White Maize",
    variety: "DK 8031 (Dekalb Hybrid)",
    acres: 2.2,
    plantingDate: "2026-06-12",
    expectedHarvestDate: "2026-10-25",
    growthStage: "Vegetative",
    healthScore: 78,
    ndviScore: 0.74,
    ndreScore: 0.49,
    soilMoisturePercent: 42,
    soilTemperatureC: 21.5,
    nitrogenStatus: "Optimal",
    irrigationMethod: "Drip",
    polygonCoordinates: [
      [0.08, 0.12],
      [0.52, 0.1],
      [0.48, 0.65],
      [0.06, 0.68],
    ],
  },
  {
    id: "zone-2",
    name: "East Plot (Legume Intercrop)",
    cropName: "Rosecoco Beans",
    variety: "GLP-2 (Mwitemania)",
    acres: 1.1,
    plantingDate: "2026-07-01",
    expectedHarvestDate: "2026-09-30",
    growthStage: "Flowering",
    healthScore: 89,
    ndviScore: 0.86,
    ndreScore: 0.62,
    soilMoisturePercent: 48,
    soilTemperatureC: 22.0,
    nitrogenStatus: "Optimal",
    irrigationMethod: "Rainfed",
    polygonCoordinates: [
      [0.55, 0.18],
      [0.92, 0.22],
      [0.88, 0.75],
      [0.52, 0.7],
    ],
  },
  {
    id: "zone-3",
    name: "South Orchard (Perennial)",
    cropName: "Hass Avocado",
    variety: "Grafted Hass Export Grade",
    acres: 0.5,
    plantingDate: "2023-04-10",
    expectedHarvestDate: "2026-11-15",
    growthStage: "Grain Filling",
    healthScore: 92,
    ndviScore: 0.82,
    ndreScore: 0.58,
    soilMoisturePercent: 50,
    soilTemperatureC: 20.8,
    nitrogenStatus: "Optimal",
    irrigationMethod: "Drip",
    polygonCoordinates: [
      [0.1, 0.72],
      [0.46, 0.7],
      [0.44, 0.94],
      [0.12, 0.95],
    ],
  },
];

export const MOCK_WEATHER: WeatherForecast = {
  temperature: 24,
  feelsLike: 25,
  humidityPercent: 78,
  windSpeedKmh: 11,
  precipitationChance: 65,
  rainForecastMmNext3Days: 28,
  forecastSummary: "Scattered afternoon showers with high overnight humidity. Ideal for grain filling, but elevate vigilance for fungal spores.",
  uvIndex: 6,
  evapotranspirationMm: 3.8,
  dailyForecast: [
    { day: "Today", date: "Sep 16", tempHigh: 24, tempLow: 14, rainProb: 65, condition: "Partly Cloudy" },
    { day: "Thu", date: "Sep 17", tempHigh: 22, tempLow: 15, rainProb: 80, condition: "Rain" },
    { day: "Fri", date: "Sep 18", tempHigh: 23, tempLow: 14, rainProb: 40, condition: "Showers" },
    { day: "Sat", date: "Sep 19", tempHigh: 25, tempLow: 13, rainProb: 15, condition: "Sunny" },
    { day: "Sun", date: "Sep 20", tempHigh: 26, tempLow: 14, rainProb: 10, condition: "Sunny" },
  ],
};

export const MOCK_DISEASE_PREDICTION: DiseasePrediction = {
  id: "pred-nlb-001",
  diseaseName: "Northern Corn Leaf Blight (Exserohilum turcicum)",
  crop: "White Maize (DK 8031)",
  affectedZoneId: "zone-1",
  affectedZoneName: "North Plot (Maize Block)",
  riskLevel: "High",
  riskPercentage: 78,
  preSymptomaticWarning: true,
  environmentalTriggers: [
    "Relative humidity >80% for 14 continuous night hours",
    "Canopy temperature between 18°C and 26°C with leaf wetness",
    "Micro-spectral NDRE dip (-0.04) detected on upper leaves by Sentinel-2",
  ],
  recommendedActions: {
    immediate: [
      "Scout lower leaf canopy in Zone 1 for elliptical, water-soaked grey-green lesions.",
      "Suspend overhead sprinkling after 3:00 PM to ensure foliage dries before dusk.",
    ],
    preventive: [
      "Apply protective contact/systemic fungicide during next dry morning window.",
      "Ensure proper row airflow by weeding bottom crop borders.",
    ],
    pcpbApprovedInputs: [
      {
        commercialName: "Ortiva Top 325 SC",
        activeIngredient: "Azoxystrobin (200g/L) + Difenoconazole (125g/L)",
        dosagePer20LKnapsack: "20 ml per 20L water",
        preHarvestIntervalDays: 14,
        estimatedCostKes: 1450,
      },
      {
        commercialName: "Ridomil Gold MZ 68 WG",
        activeIngredient: "Mefenoxam (40g/kg) + Mancozeb (640g/kg)",
        dosagePer20LKnapsack: "50 g per 20L water",
        preHarvestIntervalDays: 7,
        estimatedCostKes: 1100,
      },
    ],
    culturalPractices: [
      "Practice crop rotation with Rosecoco beans in upcoming season.",
      "Deep bury crop residues after harvest to break fungal spore life cycle.",
    ],
  },
  detectedDate: "2026-09-16 06:00 EAT",
};

export const MOCK_LEAF_DIAGNOSES: LeafDiagnosis[] = [
  {
    id: "diag-01",
    timestamp: "2026-09-14 11:20 EAT",
    imageUrl: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?w=400&auto=format&fit=crop&q=80",
    cropIdentified: "Maize (Zea mays)",
    diseaseIdentified: "Early Northern Corn Leaf Blight",
    confidenceScore: 94.2,
    severity: "Mild",
    symptomsObserved: [
      "Elongated rectangular grayish-green lesions (1.5 cm) on middle leaf tier",
      "No secondary fungal sporulation observed yet",
    ],
    prescribedTreatment: {
      chemical: "Ortiva Top 325 SC (20ml / 20L knapsack)",
      dosage: "1 knapsack per quarter acre, target upper & lower leaf sides",
      organicAlternative: "Neem oil extract (30ml) + Copper oxychloride (40g) per 20L",
      applicationIntervalDays: 10,
      safetyPrecautions: "Wear protective face mask and gloves. 14-day pre-harvest interval.",
    },
  },
  {
    id: "diag-02",
    timestamp: "2026-09-02 14:15 EAT",
    imageUrl: "https://images.unsplash.com/photo-1592417817098-8f3d6eb22509?w=400&auto=format&fit=crop&q=80",
    cropIdentified: "Common Bean (Phaseolus vulgaris)",
    diseaseIdentified: "Bean Rust (Uromyces appendiculatus)",
    confidenceScore: 91.8,
    severity: "Moderate",
    symptomsObserved: [
      "Small reddish-brown circular pustules on leaf underside",
      "Yellow halos forming around older pustules",
    ],
    prescribedTreatment: {
      chemical: "Daconil 720 SC (Chlorothalonil)",
      dosage: "40ml per 20L water",
      organicAlternative: "Wettable sulfur powder (35g / 20L)",
      applicationIntervalDays: 7,
      safetyPrecautions: "Avoid spraying during peak bee activity hours (10 AM - 2 PM).",
    },
  },
];

export const MOCK_MARKET_PRICES: KenyanMarketPrice[] = [
  {
    id: "mkt-nbi-wakulima",
    marketName: "Nairobi Wakulima (Marikiti)",
    town: "Nairobi CBD",
    county: "Nairobi",
    commodity: "Dry White Maize (90kg)",
    unit: "90kg Bag",
    priceKes: 4650,
    priceChange7DayPercent: 8.2,
    transportCostKesPerUnit: 350,
    distanceKm: 34,
    netRevenuePerBag: 4300,
    isTopRecommendation: true,
    marketDay: "Daily (Busiest Mon & Thu)",
    verifiedWholesaleBuyers: [
      { name: "Samuel Mwangi", phone: "+254 722 918 201", businessName: "Mwangi Cereals Millers", verifiedBadge: true },
      { name: "Grace Wanjiku", phone: "+254 733 445 119", businessName: "Wakulima Grain Aggregators", verifiedBadge: true },
    ],
  },
  {
    id: "mkt-thika-madaraka",
    marketName: "Thika Madaraka Market",
    town: "Thika Town",
    county: "Kiambu",
    commodity: "Dry White Maize (90kg)",
    unit: "90kg Bag",
    priceKes: 4300,
    priceChange7DayPercent: 3.5,
    transportCostKesPerUnit: 180,
    distanceKm: 18,
    netRevenuePerBag: 4120,
    isTopRecommendation: false,
    marketDay: "Tue & Fri Wholesale",
    verifiedWholesaleBuyers: [
      { name: "Peter Kariuki", phone: "+254 720 112 334", businessName: "Chania Grain Merchants", verifiedBadge: true },
    ],
  },
  {
    id: "mkt-nakuru-wakulima",
    marketName: "Nakuru Top Market",
    town: "Nakuru City",
    county: "Nakuru",
    commodity: "Dry White Maize (90kg)",
    unit: "90kg Bag",
    priceKes: 4100,
    priceChange7DayPercent: -1.2,
    transportCostKesPerUnit: 650,
    distanceKm: 145,
    netRevenuePerBag: 3450,
    isTopRecommendation: false,
    marketDay: "Mon to Sat",
    verifiedWholesaleBuyers: [
      { name: "Erick Koech", phone: "+254 711 889 001", businessName: "Rift Valley Millers", verifiedBadge: true },
    ],
  },
  {
    id: "mkt-eldoret-municipal",
    marketName: "Eldoret Main Market",
    town: "Eldoret",
    county: "Uasin Gishu",
    commodity: "Dry White Maize (90kg)",
    unit: "90kg Bag",
    priceKes: 3950,
    priceChange7DayPercent: 1.0,
    transportCostKesPerUnit: 800,
    distanceKm: 290,
    netRevenuePerBag: 3150,
    isTopRecommendation: false,
    marketDay: "Daily",
    verifiedWholesaleBuyers: [
      { name: "Kipchumba Bett", phone: "+254 725 678 123", businessName: "Highland Agri Grain Co.", verifiedBadge: true },
    ],
  },
];

export const MOCK_SACCO_OPTIONS: SaccoLoanOption[] = [
  {
    id: "sacco-kfs-01",
    institutionName: "Kiambu Farmers SACCO",
    institutionType: "SACCO",
    productName: "Kilimo Bora Seasonal Input Loan",
    category: "Input Loan",
    interestRateAnnualPercent: 10.5,
    maxAmountKes: 250000,
    repaymentTermMonths: 6,
    gracePeriodMonths: 2,
    requiresCollateral: false,
    digitalTwinCreditDiscount: 1.5,
    profileMatchPercent: 96,
    isRecommended: true,
    features: [
      "Zero physical title-deed collateral required; Digital Twin NDVI health score acts as underwriting proof",
      "Direct disbursement to verified agro-dealers via M-Pesa Till",
      "Repayment aligned with maize harvest cycle in October/November",
    ],
    eligibilityCriteria: [
      "Active farmer in Kiambu or Murang'a County",
      "Digital Twin Farm health score above 70/100",
      "SACCO membership active >3 months",
    ],
  },
  {
    id: "sacco-kwft-02",
    institutionName: "Kenya Women Microfinance Bank",
    institutionType: "Bank",
    productName: "Agri-Smart Water & Irrigation Finance",
    category: "Asset Financing",
    interestRateAnnualPercent: 12.0,
    maxAmountKes: 400000,
    repaymentTermMonths: 18,
    gracePeriodMonths: 3,
    requiresCollateral: true,
    digitalTwinCreditDiscount: 1.0,
    profileMatchPercent: 88,
    isRecommended: false,
    features: [
      "Covers drip irrigation kits, solar water pumps, and water storage tanks",
      "Supplier installation warranty included in financing package",
    ],
    eligibilityCriteria: [
      "Proof of verified water source (borehole/river riparian permit)",
      "Guarantorship from local farmer group or SACCO chapter",
    ],
  },
  {
    id: "sacco-afc-03",
    institutionName: "Agricultural Finance Corporation",
    institutionType: "Bank",
    productName: "Jiinue Kilimo Medium-Term Development",
    category: "Asset Financing",
    interestRateAnnualPercent: 9.0,
    maxAmountKes: 1000000,
    repaymentTermMonths: 36,
    gracePeriodMonths: 6,
    requiresCollateral: true,
    digitalTwinCreditDiscount: 2.0,
    profileMatchPercent: 78,
    isRecommended: false,
    features: [
      "Government-subsidized concessionary interest rate",
      "Ideal for greenhouse installation and perennial avocado orchard scaling",
    ],
    eligibilityCriteria: [
      "Minimum 2 acres under active commercial cultivation",
      "Certified 2-year yield history",
    ],
  },
  {
    id: "coop-githunguri-04",
    institutionName: "Githunguri Dairy Farmers Cooperative",
    institutionType: "Cooperative",
    productName: "Member Input Advance",
    category: "Input Loan",
    interestRateAnnualPercent: 8.5,
    maxAmountKes: 180000,
    repaymentTermMonths: 8,
    gracePeriodMonths: 2,
    requiresCollateral: false,
    digitalTwinCreditDiscount: 1.0,
    profileMatchPercent: 91,
    isRecommended: false,
    features: ["Deducted from produce payout", "No title deed"],
    eligibilityCriteria: ["Active cooperative member"],
  },
  {
    id: "bank-equity-05",
    institutionName: "Equity Bank",
    institutionType: "Bank",
    productName: "Kilimo Biashara",
    category: "Input Loan",
    interestRateAnnualPercent: 13.5,
    maxAmountKes: 500000,
    repaymentTermMonths: 12,
    gracePeriodMonths: 3,
    requiresCollateral: true,
    digitalTwinCreditDiscount: 0.5,
    profileMatchPercent: 72,
    isRecommended: false,
    features: ["Branch + M-Pesa disbursement"],
    eligibilityCriteria: ["National ID", "Twin score above 65"],
  },
];

export const MOCK_ALERTS: FarmAlert[] = [
  {
    id: "alt-1",
    title: "High Risk: Leaf Blight Spores Detected in Zone 1",
    message: "Sentinel-2 micro-index dip and 84% overnight humidity trigger early warning for Northern Corn Leaf Blight.",
    category: "Disease",
    severity: "critical",
    timestamp: "Today, 06:15 EAT",
    isRead: false,
    actionUrl: "/crop-health",
  },
  {
    id: "alt-2",
    title: "Price Surge: Nairobi Wakulima +8.2%",
    message: "Dry maize prices rose to KES 4,650 per 90kg bag due to high millers' demand in Nairobi.",
    category: "Market",
    severity: "info",
    timestamp: "Yesterday, 16:40 EAT",
    isRead: false,
    actionUrl: "/markets",
  },
  {
    id: "alt-3",
    title: "Rain Forecast: 28mm over next 48 hours",
    message: "Hold off nitrogen top-dressing until after heavy showers to avoid fertilizer leaching.",
    category: "Weather",
    severity: "warning",
    timestamp: "Sep 15, 10:00 EAT",
    isRead: true,
    actionUrl: "/dashboard",
  },
];

export const MOCK_ACTIVITIES: ActivityLog[] = [
  {
    id: "act-1",
    date: "2026-09-12",
    category: "Irrigation",
    description: "Scheduled drip irrigation for 3.5 hours on South Avocado Block (4,200L applied).",
    zoneName: "South Orchard (Avocado)",
    recordedBy: "John Mokaya",
  },
  {
    id: "act-2",
    date: "2026-08-28",
    category: "Fertilizer",
    description: "Applied CAN top-dressing fertilizer (50kg bag) along Zone 1 Maize rows.",
    zoneName: "North Plot (Maize Block)",
    costKes: 3400,
    recordedBy: "John Mokaya",
  },
  {
    id: "act-3",
    date: "2026-07-01",
    category: "Planting",
    description: "Sowed certified Rosecoco GLP-2 beans intercrop in East Plot with DAP basal fertilizer.",
    zoneName: "East Plot (Beans)",
    costKes: 4800,
    recordedBy: "John Mokaya",
  },
  {
    id: "act-4",
    date: "2026-06-12",
    category: "Planting",
    description: "Planted DK 8031 hybrid maize seed at 75cm x 25cm spacing.",
    zoneName: "North Plot (Maize Block)",
    costKes: 7200,
    recordedBy: "John Mokaya",
  },
];
