import { createFileRoute } from "@tanstack/react-router";
import { BadgeCheck, CalendarClock, CircleDollarSign, Landmark, ShieldCheck, Sparkles } from "lucide-react";
import { FarmPage, MetricCard, SectionTitle } from "@/components/agritwin/Page";
import { Button } from "@/components/ui/button";

const offers = [{ lender: "Kiambu Farmers SACCO", product: "Seasonal Input Loan", amount: "KSh 120,000", rate: "12% p.a.", term: "10 months", match: 92 }, { lender: "Agricultural Finance Corp.", product: "Smallholder Development Loan", amount: "KSh 250,000", rate: "10% p.a.", term: "24 months", match: 86 }, { lender: "Kenya Women Microfinance", product: "AgriBiz Loan", amount: "KSh 80,000", rate: "13% p.a.", term: "12 months", match: 78 }];
export const Route = createFileRoute("/_authenticated/financing")({ head: () => ({ meta: [{ title: "Farm financing — AgriTwin" }, { name: "description", content: "Discover relevant SACCO and agricultural loan options matched to your farm profile." }, { property: "og:title", content: "Farm financing — AgriTwin" }, { property: "og:description", content: "Financing options matched to your farm." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Financing });
function Financing() { return <FarmPage eyebrow="AgriFin" title="Financing" description="Relevant agricultural finance matched using your farm size, crops, production stage, and digital farm history.">
  <div className="grid gap-4 sm:grid-cols-3"><MetricCard icon={ShieldCheck} label="Finance readiness" value="Good" detail="8 of 10 profile items complete" /><MetricCard icon={CircleDollarSign} label="Estimated range" value="KSh 80k–250k" detail="Across your current matches" tone="earth" /><MetricCard icon={CalendarClock} label="Next harvest" value="24 days" detail="Projected from planting date" tone="sky" /></div>
  <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_19rem]"><div><SectionTitle title="Recommended for your farm" detail="3 suitable options" /><div className="space-y-4">{offers.map((o, i) => <article key={o.product} className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className={`grid size-11 shrink-0 place-items-center rounded-xl ${i === 0 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}><Landmark className="size-5" /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{o.product}</h2>{i === 0 && <span className="rounded-full bg-primary/15 px-2 py-1 text-[10px] font-semibold text-primary">BEST MATCH</span>}</div><p className="mt-1 text-sm text-muted-foreground">{o.lender}</p></div></div><div className="sm:text-right"><p className="text-xl font-semibold">{o.amount}</p><p className="text-xs text-primary">{o.match}% profile match</p></div></div><div className="mt-5 grid grid-cols-2 gap-4 border-t border-border pt-4 sm:grid-cols-3"><div><p className="text-xs text-muted-foreground">Interest</p><p className="mt-1 text-sm font-medium">{o.rate}</p></div><div><p className="text-xs text-muted-foreground">Term</p><p className="mt-1 text-sm font-medium">{o.term}</p></div><Button variant="outline" className="col-span-2 rounded-xl sm:col-span-1">View details</Button></div></article>)}</div></div>
  <aside className="h-fit rounded-2xl border border-primary/30 bg-primary/10 p-5"><Sparkles className="size-6 text-primary" /><h2 className="mt-4 font-semibold">Why these match</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Your 3.8-acre mapped farm, maize crop, healthy vegetation trend, and completed profile strengthen your eligibility.</p><div className="mt-5 space-y-3">{["Farm boundary verified", "Crop cycle recorded", "Contact verified", "Production history needed"].map((x, i) => <p key={x} className="flex items-center gap-2 text-sm"><BadgeCheck className={`size-4 ${i === 3 ? "text-muted-foreground" : "text-primary"}`} />{x}</p>)}</div><Button className="mt-6 w-full rounded-xl">Improve my profile</Button></aside></div>
 </FarmPage>; }