import { createFileRoute } from "@tanstack/react-router";
import { ArrowDownRight, ArrowUpRight, MapPin, Navigation, Store, TrendingUp } from "lucide-react";
import { FarmPage, SectionTitle } from "@/components/agritwin/Page";
import { Button } from "@/components/ui/button";

const markets = [{ name: "Nairobi Wakulima", town: "Nairobi", distance: "38 km", price: 4650, change: 8.2 }, { name: "Kangari Market", town: "Murang'a", distance: "44 km", price: 4380, change: 3.1 }, { name: "Thika Main Market", town: "Thika", distance: "18 km", price: 4260, change: -1.4 }, { name: "Githurai Market", town: "Kiambu", distance: "26 km", price: 4510, change: 5.6 }];
export const Route = createFileRoute("/_authenticated/markets")({ head: () => ({ meta: [{ title: "Market intelligence — AgriTwin" }, { name: "description", content: "Compare Kenyan crop prices and identify better selling opportunities for your harvest." }, { property: "og:title", content: "Market intelligence — AgriTwin" }, { property: "og:description", content: "Compare crop prices across nearby markets." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Markets });
function Markets() { return <FarmPage eyebrow="Kenya market watch" title="Market intelligence" description="Compare current prices, distance, and momentum before deciding where and when to sell." action={<Button variant="outline" className="rounded-xl"><MapPin /> Near Kiambu</Button>}>
  <section className="flex flex-col justify-between gap-5 rounded-2xl border border-primary/30 bg-primary/10 p-6 md:flex-row md:items-center"><div><p className="text-xs font-semibold uppercase text-primary">Best opportunity this week</p><h2 className="mt-2 text-2xl font-semibold">Nairobi Wakulima Market</h2><p className="mt-2 text-sm text-muted-foreground">Selling 10 bags here could earn about KSh 3,900 more than Thika after estimated transport.</p></div><div className="shrink-0 md:text-right"><p className="text-3xl font-semibold">KSh 4,650</p><p className="text-xs text-muted-foreground">per 90 kg bag · dry maize</p><Button className="mt-4 rounded-xl"><Navigation /> Plan selling trip</Button></div></section>
  <div className="mt-7"><SectionTitle title="Maize prices near you" detail="Updated today at 08:30" /><div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="hidden grid-cols-[1.5fr_.7fr_.7fr_.5fr] gap-4 border-b border-border px-5 py-3 text-xs text-muted-foreground sm:grid"><span>Market</span><span>Distance</span><span>Price / 90 kg</span><span>7 day</span></div>{markets.map((m, i) => <article key={m.name} className="grid gap-3 border-b border-border p-5 last:border-0 sm:grid-cols-[1.5fr_.7fr_.7fr_.5fr] sm:items-center"><div className="flex items-center gap-3"><span className={`grid size-10 place-items-center rounded-xl ${i === 0 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}><Store className="size-4" /></span><div><p className="text-sm font-semibold">{m.name}</p><p className="text-xs text-muted-foreground">{m.town}</p></div></div><p className="text-sm text-muted-foreground">{m.distance}</p><p className="font-semibold">KSh {m.price.toLocaleString()}</p><p className={`flex items-center gap-1 text-sm font-medium ${m.change > 0 ? "text-primary" : "text-risk"}`}>{m.change > 0 ? <ArrowUpRight className="size-4" /> : <ArrowDownRight className="size-4" />}{Math.abs(m.change)}%</p></article>)}</div></div>
  <section className="mt-6 rounded-2xl border border-border bg-card p-5"><div className="flex gap-3"><TrendingUp className="mt-0.5 size-5 text-earth" /><div><h2 className="font-semibold">Harvest timing insight</h2><p className="mt-1 text-sm leading-relaxed text-muted-foreground">Prices may strengthen over the next two weeks as local supply tightens. Your projected harvest window begins in 24 days.</p></div></div></section>
 </FarmPage>; }